# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: git-raycast
report_sizes: true

before:
  hooks:
    - go mod tidy
    # Generate completions
    - make completions

builds:
  - binary: git-raycast
    main: ./git-raycast/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

universal_binaries:
  - replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: "{{ .ProjectName }}"
    formats:
      - tar.gz
    files:
      - "LICENSE"
      - "README.md"
      - src: "completions.build/*"
        dst: "."

homebrew_casks:
  - name: git-raycast
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.COMMITTER_TOKEN }}"
    commit_author:
      name: "{{ .Env.GITHUB_ACTOR }}"
      email: "{{ .Env.GITHUB_ACTOR }}@users.noreply.github.com"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    description: "Automate git using Raycast AI"
    url:
      verified: "github.com/{{ .Env.GITHUB_REPOSITORY }}"
    binaries:
      - git-raycast
    completions:
      bash: git-raycast.bash
      zsh: git-raycast.zsh
      fish: git-raycast.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-raycast"]
          end

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  draft: false
  include_meta: true
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    Checksum of release:

    ```
    {{ .Checksums }}```

    > Raycast AI is a product of [Raycast](https://raycast.com).

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
