name: Go Build and Release

env:
  COMMAND_NAME: git-raycast

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag-name:
        description: "The git tag name to bump the formula to"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run GoReleaser Check
        uses: goreleaser/goreleaser-action@v6
        with:
          args: check

      - name: Get version
        id: version
        run: |
          VERSION=$(echo "${{ github.event.inputs.tag-name || github.ref }}" | sed -n 's/refs\/tags\/v\(.*\)/\1/p')
          if [[ -z "$VERSION" ]]; then
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
