name: Go Build and Release

env:
  COMMAND_NAME: git-raycast

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag-name:
        description: "The git tag name to bump the formula to"
        required: true

permissions:
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  release:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Get version
        id: version
        run: |
          VERSION=$(echo "${{ github.event.inputs.tag-name || github.ref }}" | sed -n 's/refs\/tags\/v\(.*\)/\1/p')
          if [[ -z "$VERSION" ]]; then
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
