name: Check Build

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  check:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
