name: Check Build

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
  pull_request:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/setup.yml

      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v2.5.0
          args: build --clean --snapshot
